apiVersion: vendir.k14s.io/v1alpha1
kind: Config

minimumRequiredVersion: 0.26.0

directories:
  - path: packages/educates/v3.3.2/bin
    contents:
      - path: .
        githubRelease:
          # https://github.com/educates/educates-training-platform/releases/download/v3.3.2/educates-linux-amd64
          slug: educates/educates-training-platform
          tag: 3.3.2
          disableAutoChecksumValidation: true
        includePaths:
          - educates-linux-amd64
          - educates-linux-arm64
  - path: packages/educates/v3.2.2/bin
    contents:
      - path: .
        githubRelease:
          # https://github.com/educates/educates-training-platform/releases/download/v3.2.2/educates-linux-amd64
          slug: educates/educates-training-platform
          tag: 3.2.2
          disableAutoChecksumValidation: true
        includePaths:
          - educates-linux-amd64
          - educates-linux-arm64
  - path: packages/educates/v3.1.0/bin
    contents:
      - path: .
        githubRelease:
          # https://github.com/educates/educates-training-platform/releases/download/v3.1.0/educates-linux-amd64
          slug: educates/educates-training-platform
          tag: 3.1.0
          disableAutoChecksumValidation: true
        includePaths:
          - educates-linux-amd64
          - educates-linux-arm64
  - path: packages/educates/v3.0.1/bin
    contents:
      - path: .
        githubRelease:
          # https://github.com/educates/educates-training-platform/releases/download/v3.0.1/educates-linux-amd64
          slug: educates/educates-training-platform
          tag: 3.0.1
          disableAutoChecksumValidation: true
        includePaths:
          - argocd-linux-amd64
          - educates-linux-arm64
  - path: packages/argocd/v2.10.6/bin
    contents:
      - path: .
        githubRelease:
          # https://github.com/argoproj/argo-cd/releases/download/v2.10.6/argocd-linux-amd64
          slug: argoproj/argo-cd
          tag: v2.10.6
          disableAutoChecksumValidation: true
        includePaths:
          - argocd-linux-amd64
  - path: packages/crane/v0.19.1/bin
    contents:
      - path: .
        githubRelease:
          # https://github.com/google/go-containerregistry/releases/download/v0.19.1/go-containerregistry_Linux_x86_64.tar.gz
          slug: google/go-containerregistry
          tag: v0.19.1
          disableAutoChecksumValidation: true
          assetNames: ["go-containerregistry_Linux_x86_64.tar.gz"]
          unpackArchive:
            path: go-containerregistry_Linux_x86_64.tar.gz
        includePaths:
          - crane
        excludePaths:
          - LICENSE
  - path: packages/vscode-java-tools/v0.29.2/extensions/redhat.java-arm64
    contents:
      - path: .
        http:
          url: https://github.com/redhat-developer/vscode-java/releases/download/v1.42.0/java-linux-arm64-1.42.0-561.vsix
          disableUnpack: true
  - path: packages/vscode-java-tools/v0.29.2/extensions/redhat.java-amd64
    contents:
      - path: .
        http:
          url: https://github.com/redhat-developer/vscode-java/releases/download/v1.42.0/java-linux-x64-1.42.0-561.vsix
          disableUnpack: true
  - path: packages/vscode-java-tools/v0.29.2/extensions/vscjava.vscode-java-dependency
    contents:
      - path: .
        http:
          url: https://open-vsx.org/api/vscjava/vscode-java-dependency/0.24.1/file/vscjava.vscode-java-dependency-0.24.1.vsix
          disableUnpack: true
  - path: packages/vscode-java-tools/v0.29.2/extensions/vscjava.vscode-java-test
    contents:
      - path: .
        http:
          url: https://open-vsx.org/api/vscjava/vscode-java-test/0.43.1/file/vscjava.vscode-java-test-0.43.1.vsix
          disableUnpack: true
  - path: packages/vscode-java-tools/v0.29.2/extensions/vscjava.vscode-maven
    contents:
      - path: .
        http:
          url: https://open-vsx.org/api/vscjava/vscode-maven/0.44.0/file/vscjava.vscode-maven-0.44.0.vsix
          disableUnpack: true
  - path: packages/vscode-java-tools/v0.29.2/extensions/vscjava.vscode-gradle
    contents:
      - path: .
        http:
          url: https://open-vsx.org/api/vscjava/vscode-gradle/3.15.0/file/vscjava.vscode-gradle-3.15.0.vsix
          disableUnpack: true
  - path: packages/vscode-java-tools/v0.29.2/extensions/vscjava.vscode-java-debug
    contents:
      - path: .
        http:
          url: https://open-vsx.org/api/vscjava/vscode-java-debug/0.58.2/file/vscjava.vscode-java-debug-0.58.2.vsix
          disableUnpack: true
  - path: packages/vscode-java-tools/v0.29.2/extensions/vscjava.vscode-java-pack
    contents:
      - path: .
        http:
          url: https://open-vsx.org/api/vscjava/vscode-java-pack/0.29.2/file/vscjava.vscode-java-pack-0.29.2.vsix
          disableUnpack: true
