apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "sample-toolhive-workshop-"
spec:
  title: "Toolhive extensions sample workshop for Educates"
  description: "Workshop to sample the Toolhive Educates extension package"
  publish:
    image: "$(image_repository)/sample-toolhive-workshop-files:$(workshop_version)"
  workshop:
    files:
    - image:
        url: "$(image_repository)/sample-toolhive-workshop-files:$(workshop_version)"
      includePaths:
      - /workshop/**
      - /exercises/**
      - /README.md
    packages:
      - name: toolhive
        files:
          - path: .
            image:
              url: $(image_repository)/toolhive:v0.1.7
  session:
    namespaces:
      budget: large
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
      console:
        enabled: false
      docker:
        enabled: false
      registry:
        enabled: false
      vcluster:
        enabled: false