apiVersion: vendir.k14s.io/v1alpha1
kind: Config

minimumRequiredVersion: 0.26.0

directories:
  - path: bin
    contents:
      - path: .
        githubRelease:
          # https://github.com/loft-sh/vcluster/releases/download/v0.30.2/vcluster-linux-amd64
          slug: loft-sh/vcluster
          tag: v0.30.2
          disableAutoChecksumValidation: true
        includePaths:
          - vcluster-linux-amd64
          - vcluster-linux-arm64