apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "sample-vscode-roo-code-workshop"
spec:
  title: "VSCode Roo Code Extensions Sample Workshop"
  description: "Workshop to sample the VSCode Roo Code extensions"
  publish:
    image: "$(image_repository)/sample-vscode-roo-code-workshop-files:$(workshop_version)"
  workshop:
    files:
    - image:
        url: "$(image_repository)/sample-vscode-roo-code-workshop-files:$(workshop_version)"
      includePaths:
      - /workshop/**
    packages:
      - name: vscode-roo-code
        files:
          - path: .
            image:
              url: $(image_repository)/vscode-roo-code:v3.22.5
  session:
    namespaces:
      budget: large
    resources:
      memory: 3Gi
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
      console:
        enabled: false
      docker:
        enabled: false
      registry:
        enabled: false
      vcluster:
        enabled: false