apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "sample-github-extension-workshop"
spec:
  title: "GitHub CLI Extensions sample workshop"
  description: "Workshop to sample the GitHub CLI extension for Educates"
  publish:
    image: "$(image_repository)/sample-github-extension-workshop-files:$(workshop_version)"
  workshop:
    files:
    - image:
        url: "$(image_repository)/sample-github-extension-workshop-files:$(workshop_version)"
      includePaths:
      - /workshop/**
      - /exercises/**
      - /README.md
    packages:
      - name: github
        files:
          - path: .
            image:
              url: $(image_repository)/github:v2.74.2
  session:
    namespaces:
      budget: large
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
      console:
        enabled: false
      docker:
        enabled: false
      registry:
        enabled: false
      vcluster:
        enabled: false