name: Publish packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Carvel tools
        shell: bash
        run: curl -L https://carvel.dev/install.sh | bash

      # - name: Calculate variables
      #   shell: bash
      #   run: |
      #     REPOSITORY_OWNER=${{github.repository_owner}}
      #     echo "REPOSITORY_OWNER=${REPOSITORY_OWNER,,}" >>${GITHUB_ENV}
      #     echo "REPOSITORY_TAG=${GITHUB_REF##*/}" >>${GITHUB_ENV}
      #     echo "REPOSITORY_SHA_TAG=sha-${GITHUB_SHA::7}" >>${GITHUB_ENV}

      - name: Iterate over directories
        run: |
          PROJECT_DIR=$(pwd)

          PACKAGE_DIRS=$(find packages -mindepth 1 -maxdepth 1 -type d -print)
          for PACKAGE_DIR in ${PACKAGE_DIRS[@]}; do
            VERSION_DIRS=$(find $PACKAGE_DIR/v* -mindepth 0 -maxdepth 0 -type d -print)
            for VERSION_DIR in ${VERSION_DIRS[@]}; do
              PACKAGE=$(basename $PACKAGE_DIR)
              VERSION=$(echo $VERSION_DIR | cut -d/ -f3)
              echo "Publishing package $PACKAGE/$VERSION from $VERSION_DIR"
                echo "Syncing package $PACKAGE"
                cd packages/$PACKAGE/$VERSION
                vendir sync
                $PROJECT_DIR/scripts/fix-permissions.sh || true
                cd $PROJECT_DIR
                echo "Synced package $PACKAGE"
                echo "Pushing package $PACKAGE:$VERSION from $VERSION_DIR into ghcr.io/${{github.repository}}/$PACKAGE:$VERSION"
                imgpkg push -i ghcr.io/${{github.repository}}/$PACKAGE:$VERSION -f $VERSION_DIR --registry-username=${{github.actor}} --registry-password=${{secrets.GITHUB_TOKEN}}
                echo "Pushed package $PACKAGE:$VERSION from $VERSION_DIR into ghcr.io/${{github.repository}}/$PACKAGE:$VERSION"
            done
          done
